Updated README for the change in default config
digio/serverless-simple-alias pull request #3
Opened 2023-09-05 14:36 UTC by vibhoragarwal

Updated README for change in default configurations

2023-09-05 21:30 UTC, uglow requested changes
The readme looks good, but the IDE file cannot be added to this repo. If you could add the file to the .gitignore, then we can merge.

2023-09-05 21:30 UTC, uglow commented on .idea/workspace.xml
IDE files should be ignored by git

2023-09-06 05:35 UTC, vibhoragarwal commented on .idea/workspace.xml
Yes.

2023-09-06 05:47 UTC, uglow approved these changes
Looks good - thanks for contributing!

2023-09-06 05:47 UTC, merged

2023-09-06 05:55 UTC, vibhoragarwal commented
Thanks Brett for your plugin, very helpful indeed..